[phases.install]
cmds = [
  "npm install --prefix frontend",
  "npm install --prefix backend"
]

[phases.build]
cmds = [
  "npm run build --prefix frontend",
  "cp -r frontend/dist backend/public",
  "cd backend && npx prisma generate && npx prisma db push --accept-data-loss && npm run build"
]

[start]
cmd = "node backend/dist/server.js"
